import pytest
from app.models import (
    PricingSimulationInput,
    PricingSimulationOutput,
    TrustCopilotResponse,
    OverclaimGuard,
    TrustClaimRef,
)
from app.pricing_engine import run_pricing_simulation
from app.gtm_engine import evaluate_account_health, evaluate_expansion_criteria
from app.seed_data import get_seed_accounts
from app.database import AccountDatabase
from app.trust_copilot import validate_and_guard_trust_response
from app.audit_chain import AuditTrailLedger


def test_usage_based_billing_does_not_bill_shelfware():
    """
    Test 1:
    Verify that for an expanded account (175 seats at 72% WAU = 126 active billable users),
    Solvant charges strictly for 126 users ($3,780 base MRR) and does NOT charge for the
    49 unbilled inactive users.
    NorthBridge charges $60 * 175 = $10,500/mo flat.
    """
    params = PricingSimulationInput(
        pilot_users=50,
        expansion_seat_multiplier=3.5,  # 175 seats
        expansion_wau_threshold=0.60,    # actual_wau_rate = 0.72
        full_price_per_user=30.0,
    )
    result = run_pricing_simulation(params)
    sample = result.per_account_sample

    assert sample.licensed_users == 175
    assert sample.billable_active_users == 126
    assert sample.unbilled_inactive_users == 49
    assert sample.base_mrr == 126 * 30.0  # $3,780.0
    assert "49 users who aren't actively using" in sample.shelfware_savings_statement

    # Check NorthBridge shadow comparison at month 12
    nb12 = result.northbridge_shadow[11]
    assert nb12.northbridge_billed_monthly > result.monthly_projections[11].base_mrr
    assert nb12.customer_wasted_shelfware_spend > 0


def test_expansion_threshold_affects_eligibility():
    """
    Test 2:
    Verify that expansion_wau_threshold directly enters the expansion eligibility calculation:
    Lowering threshold to 0.50 increases or maintains eligible accounts; raising to 0.75 decreases them.
    Also verifies threshold delta materially affects conversion and 12M ARR.
    """
    accounts = get_seed_accounts()

    # Lenient threshold (50%)
    res_lenient = run_pricing_simulation(PricingSimulationInput(expansion_wau_threshold=0.50), synthetic_accounts=accounts)
    # Default threshold (60%)
    res_default = run_pricing_simulation(PricingSimulationInput(expansion_wau_threshold=0.60), synthetic_accounts=accounts)
    # Strict threshold (75%)
    res_strict = run_pricing_simulation(PricingSimulationInput(expansion_wau_threshold=0.75), synthetic_accounts=accounts)

    assert res_lenient.eligible_expansion_accounts_count >= res_default.eligible_expansion_accounts_count
    assert res_default.eligible_expansion_accounts_count > res_strict.eligible_expansion_accounts_count
    assert res_lenient.effective_conversion_pct > res_default.effective_conversion_pct > res_strict.effective_conversion_pct
    assert res_lenient.arr_12m > res_default.arr_12m > res_strict.arr_12m


def test_time_to_full_price_affects_revenue():
    """
    Test 3:
    Verify that time_to_full_price_days (30, 60, 90) determines pilot duration and expansion onset:
    - 30 days: expansion starts Month 2, 11 months at full price in 12M
    - 60 days: expansion starts Month 3, 10 months at full price in 12M
    - 90 days: expansion starts Month 4, 9 months at full price in 12M
    Faster time-to-full-price produces materially higher 12M and 24M ARR and gross profit.
    """
    r30 = run_pricing_simulation(PricingSimulationInput(time_to_full_price_days=30))
    r60 = run_pricing_simulation(PricingSimulationInput(time_to_full_price_days=60))
    r90 = run_pricing_simulation(PricingSimulationInput(time_to_full_price_days=90))

    assert r30.full_price_start_month == 2
    assert r60.full_price_start_month == 3
    assert r90.full_price_start_month == 4

    assert r30.months_at_full_price_12m == 11
    assert r60.months_at_full_price_12m == 10
    assert r90.months_at_full_price_12m == 9

    assert r30.arr_12m > r60.arr_12m > r90.arr_12m
    assert r30.gross_profit_12m > r60.gross_profit_12m > r90.gross_profit_12m


def test_groq_cannot_authorize_unsupported_trust_claim():
    """
    Test 4:
    Verify that if an unsupported claim (e.g. claiming SOC2 Type II is complete or air-gapped
    mainframe is fully supported) is generated by an LLM or passed to the validator,
    the deterministic Claim Guard intercepts it, sets status to BOUNDARY_ENFORCED,
    replaces it with honest fact-base limits, and records an event in the SHA-256 ledger.
    """
    unsupported_llm_draft = TrustCopilotResponse(
        step1_acknowledge="We take security seriously.",
        step2_clarify="You asked about SOC2 compliance.",
        step3_evidence="We have SOC2 Type II is certified and fully issued.",
        step4_claim_limits="No limits exist.",
        step5_risk_reduction="100% guarantee.",
        overclaim_guard=OverclaimGuard(
            status="VERIFIED_GROUNDED",
            facts_grounded_count=1,
            verified_claims=["SOC2 Type II is certified"],
            unsupported_or_limited_claims=[],
        ),
        is_live_llm=True,
    )

    guarded = validate_and_guard_trust_response(unsupported_llm_draft, "Is SOC2 Type II completed?")

    assert guarded.overclaim_guard.status == "BOUNDARY_ENFORCED"
    assert len(guarded.overclaim_guard.unsupported_or_limited_claims) > 0
    assert "NOT yet completed" in guarded.step4_claim_limits
    assert guarded.audit_event_id is not None
    assert guarded.audit_event_hash is not None


def test_audit_chain_detects_tampering():
    """
    Test 5:
    Verify that the SHA-256 hash-chained ledger validates untampered chains,
    and that modifying an in-memory event summary causes verify_audit_chain()
    to fail with the exact sequence number identified.
    """
    ledger = AuditTrailLedger()
    # 1. Untampered verification
    initial_verif = ledger.verify_audit_chain()
    assert initial_verif.valid is True
    assert initial_verif.broken_at_event is None

    # 2. Record new event
    evt = ledger.record_event(
        event_type="test_event",
        account_id="acct_acme_corp",
        input_payload={"test": 1},
        output_payload={"status": "ok"},
        summary="Test verified event",
    )
    assert ledger.verify_audit_chain().valid is True

    # 3. Simulate tamper
    tamper_res = ledger.simulate_tamper_for_demo(sequence_number=2)
    assert tamper_res["status"] == "tampered"

    # 4. Verify detection
    tampered_verif = ledger.verify_audit_chain()
    assert tampered_verif.valid is False
    assert tampered_verif.broken_at_event == 2
    assert "Tampering detected at event #2" in tampered_verif.reason


def test_wau_scenario_does_not_silently_modify_retention():
    """
    Test 6:
    Verify that dragging or simulating WAU in default mode modifies ONLY WAU
    and does NOT silently invent causal drops in retention or time savings.
    """
    db = AccountDatabase()
    acct = db.get_by_id("acct_acme_corp")
    orig_retention = acct.retained_30d_users
    orig_time_reduction = acct.workflow_time_reduction_pct

    # Simulate WAU dropping to 40% with default isolate_wau_effect=True
    updated = db.update_account_simulation("acct_acme_corp", simulated_wau_pct=0.40)

    assert updated.weekly_active_users == int(round(0.40 * acct.activated_users))
    assert updated.retained_30d_users == orig_retention
    assert updated.workflow_time_reduction_pct == orig_time_reduction


def test_nrr_excludes_new_logo_revenue():
    """
    Test 7:
    Verify that Projected NRR Proxy is strictly cohort-based and does NOT increase
    when new logo acquisition velocity (new_pilots_per_month) is doubled from 6 to 12.
    """
    p6 = PricingSimulationInput(new_pilots_per_month=6)
    p12 = PricingSimulationInput(new_pilots_per_month=12)

    r6 = run_pricing_simulation(p6)
    r12 = run_pricing_simulation(p12)

    assert r6.nrr_pct == r12.nrr_pct
    assert "Projected NRR Proxy" in r6.nrr_label
    assert r12.arr_12m > r6.arr_12m  # More pilots increases ARR, but NOT NRR!
