from typing import List
from app.models import Account, WeeklyLog


def generate_weekly_logs(account_id: str, wau_history: List[float], base_users: int, base_time_saved: float) -> List[WeeklyLog]:
    logs = []
    dates = [
        "2026-07-07", "2026-07-14", "2026-07-21", "2026-07-28",
        "2026-08-04", "2026-08-11", "2026-08-18", "2026-08-25"
    ]
    for i, wau_pct in enumerate(wau_history):
        active_u = int(round(wau_pct * base_users))
        tasks_started = active_u * 18 + (i * 12)
        tasks_completed = int(tasks_started * 0.94)
        active_mins = round(42.0 + (wau_pct * 30.0), 1)
        ai_calls = tasks_started * 3 + 20
        successful_outputs = int(tasks_completed * 0.96)
        time_saved = min(0.35, max(0.05, base_time_saved * (0.8 + (i * 0.05))))
        feedback = min(5.0, max(3.0, 3.8 + (wau_pct * 1.2)))

        logs.append(
            WeeklyLog(
                week_number=i + 1,
                date=dates[i % len(dates)],
                active_users=active_u,
                tasks_started=tasks_started,
                tasks_completed=tasks_completed,
                active_minutes_avg=active_mins,
                ai_calls=ai_calls,
                successful_outputs=successful_outputs,
                time_saved_pct=round(time_saved, 3),
                feedback_score=round(feedback, 1),
            )
        )
    return logs


def get_seed_accounts() -> List[Account]:
    accounts_data = [
        # =========================================================================
        # 8 EXPANSION READY ACCOUNTS (Health Score >= 70, Verdict: EXPAND)
        # =========================================================================
        {
            "id": "acct_acme_corp",
            "name": "Acme Corp",
            "industry": "Enterprise Manufacturing & Tech",
            "tier": "Enterprise (Global 500)",
            "pilot_start_date": "2026-07-01",
            "pilot_days_elapsed": 56,
            "invited_users": 50,
            "activated_users": 48,
            "weekly_active_users": 41,  # 85.4% WAU
            "retained_30d_users": 42,   # 87.5% 30d retention
            "workflow_time_reduction_pct": 0.28,  # 28% reduction
            "monthly_verified_outputs": 740,
            "satisfaction_score": 4.7,
            "workflow_runs_monthly": 6800,
            "weekly_wau_history": [0.65, 0.70, 0.74, 0.77, 0.79, 0.82, 0.84, 0.85],
            "stage": "Expansion Ready",
            "champion_name": "Sarah Lin",
            "champion_title": "Director of FP&A Operations",
            "buyer_title": "VP Global Finance",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_meridian_financial",
            "name": "Meridian Financial",
            "industry": "Financial Services & Wealth",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-05",
            "pilot_days_elapsed": 52,
            "invited_users": 50,
            "activated_users": 47,
            "weekly_active_users": 39,
            "retained_30d_users": 40,
            "workflow_time_reduction_pct": 0.26,
            "monthly_verified_outputs": 690,
            "satisfaction_score": 4.6,
            "workflow_runs_monthly": 6100,
            "weekly_wau_history": [0.62, 0.66, 0.71, 0.74, 0.76, 0.79, 0.81, 0.83],
            "stage": "Expansion Ready",
            "champion_name": "Marcus Vance",
            "champion_title": "Head of Strategic Planning",
            "buyer_title": "Chief Financial Officer",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_apex_logistics",
            "name": "Apex Global Logistics",
            "industry": "Transportation & Supply Chain",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-10",
            "pilot_days_elapsed": 48,
            "invited_users": 50,
            "activated_users": 45,
            "weekly_active_users": 36,
            "retained_30d_users": 37,
            "workflow_time_reduction_pct": 0.24,
            "monthly_verified_outputs": 610,
            "satisfaction_score": 4.5,
            "workflow_runs_monthly": 5400,
            "weekly_wau_history": [0.58, 0.62, 0.68, 0.71, 0.73, 0.76, 0.78, 0.80],
            "stage": "Expansion Ready",
            "champion_name": "Elena Rostova",
            "champion_title": "Director of Operational Finance",
            "buyer_title": "VP Finance & Supply Chain",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_crestview_fin",
            "name": "Crestview Capital Partners",
            "industry": "Private Equity & Asset Mgmt",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-08",
            "pilot_days_elapsed": 50,
            "invited_users": 50,
            "activated_users": 46,
            "weekly_active_users": 38,
            "retained_30d_users": 38,
            "workflow_time_reduction_pct": 0.25,
            "monthly_verified_outputs": 650,
            "satisfaction_score": 4.6,
            "workflow_runs_monthly": 5800,
            "weekly_wau_history": [0.60, 0.65, 0.69, 0.73, 0.75, 0.78, 0.80, 0.82],
            "stage": "Expansion Ready",
            "champion_name": "David Chen",
            "champion_title": "Portfolio Operations Principal",
            "buyer_title": "Managing Partner & CFO",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_vanguard_retail",
            "name": "Vanguard Retail Brands",
            "industry": "Omnichannel Retail & FMCG",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-03",
            "pilot_days_elapsed": 54,
            "invited_users": 50,
            "activated_users": 48,
            "weekly_active_users": 40,
            "retained_30d_users": 41,
            "workflow_time_reduction_pct": 0.27,
            "monthly_verified_outputs": 710,
            "satisfaction_score": 4.7,
            "workflow_runs_monthly": 6400,
            "weekly_wau_history": [0.64, 0.68, 0.72, 0.75, 0.78, 0.81, 0.83, 0.84],
            "stage": "Expansion Ready",
            "champion_name": "Claire Dupont",
            "champion_title": "Senior Director Commercial Finance",
            "buyer_title": "Chief Financial Officer",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_solaris_energy",
            "name": "Solaris Clean Energy",
            "industry": "Renewable Energy & Infrastructure",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-06",
            "pilot_days_elapsed": 51,
            "invited_users": 50,
            "activated_users": 45,
            "weekly_active_users": 37,
            "retained_30d_users": 38,
            "workflow_time_reduction_pct": 0.23,
            "monthly_verified_outputs": 590,
            "satisfaction_score": 4.5,
            "workflow_runs_monthly": 5200,
            "weekly_wau_history": [0.60, 0.63, 0.67, 0.71, 0.74, 0.77, 0.79, 0.82],
            "stage": "Expansion Ready",
            "champion_name": "Raj Patel",
            "champion_title": "Head of Project Finance Analytics",
            "buyer_title": "VP Corporate Controller",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_baxter_pharma",
            "name": "Baxter BioPharma",
            "industry": "Pharmaceuticals & Clinical",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-07",
            "pilot_days_elapsed": 49,
            "invited_users": 50,
            "activated_users": 46,
            "weekly_active_users": 38,
            "retained_30d_users": 39,
            "workflow_time_reduction_pct": 0.25,
            "monthly_verified_outputs": 630,
            "satisfaction_score": 4.6,
            "workflow_runs_monthly": 5600,
            "weekly_wau_history": [0.61, 0.65, 0.69, 0.72, 0.74, 0.76, 0.79, 0.82],
            "stage": "Expansion Ready",
            "champion_name": "Dr. Emily Watson",
            "champion_title": "R&D Budget & Finance Director",
            "buyer_title": "SVP Finance & Operations",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_zenith_logistics",
            "name": "Zenith Freight Solutions",
            "industry": "Logistics & Fleet Analytics",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-11",
            "pilot_days_elapsed": 47,
            "invited_users": 50,
            "activated_users": 44,
            "weekly_active_users": 35,
            "retained_30d_users": 36,
            "workflow_time_reduction_pct": 0.22,
            "monthly_verified_outputs": 570,
            "satisfaction_score": 4.4,
            "workflow_runs_monthly": 4900,
            "weekly_wau_history": [0.58, 0.62, 0.66, 0.70, 0.72, 0.74, 0.76, 0.79],
            "stage": "Expansion Ready",
            "champion_name": "Dmitri Volkov",
            "champion_title": "Fleet Cost Analytics Lead",
            "buyer_title": "VP Finance",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },

        # =========================================================================
        # 10 HEALTHY BUT WATCH ACCOUNTS (Health Score 40-69, Verdict: HOLD)
        # =========================================================================
        {
            "id": "acct_nova_industries",
            "name": "Nova Industries",
            "industry": "Industrial Automation & Robotics",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-16",
            "pilot_days_elapsed": 42,
            "invited_users": 50,
            "activated_users": 39,
            "weekly_active_users": 24,  # Boundary case ~61.5% WAU
            "retained_30d_users": 25,
            "workflow_time_reduction_pct": 0.16,  # Just under 20%
            "monthly_verified_outputs": 410,
            "satisfaction_score": 4.1,
            "workflow_runs_monthly": 3800,
            "weekly_wau_history": [0.58, 0.60, 0.62, 0.61, 0.60, 0.61, 0.60, 0.61],
            "stage": "Healthy but Watch",
            "champion_name": "Gregory Thorne",
            "champion_title": "Director of Manufacturing Finance",
            "buyer_title": "VP Operational Finance",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_strata_networks",
            "name": "Strata Cloud & Networks",
            "industry": "Enterprise SaaS & Cloud",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-20",
            "pilot_days_elapsed": 38,
            "invited_users": 50,
            "activated_users": 38,
            "weekly_active_users": 23,
            "retained_30d_users": 24,
            "workflow_time_reduction_pct": 0.15,
            "monthly_verified_outputs": 390,
            "satisfaction_score": 4.1,
            "workflow_runs_monthly": 3500,
            "weekly_wau_history": [0.56, 0.58, 0.60, 0.59, 0.61, 0.60, 0.59, 0.60],
            "stage": "Healthy but Watch",
            "champion_name": "Liam O'Connor",
            "champion_title": "FP&A Manager",
            "buyer_title": "VP Finance",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_beacon_health",
            "name": "Beacon Regional Health",
            "industry": "Healthcare Providers",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-22",
            "pilot_days_elapsed": 36,
            "invited_users": 50,
            "activated_users": 37,
            "weekly_active_users": 22,
            "retained_30d_users": 23,
            "workflow_time_reduction_pct": 0.14,
            "monthly_verified_outputs": 360,
            "satisfaction_score": 4.0,
            "workflow_runs_monthly": 3200,
            "weekly_wau_history": [0.54, 0.57, 0.59, 0.58, 0.60, 0.59, 0.58, 0.59],
            "stage": "Healthy but Watch",
            "champion_name": "Patricia Simmons",
            "champion_title": "Clinical Budget Lead",
            "buyer_title": "CFO",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_solaris_semi",
            "name": "Solaris Semiconductor",
            "industry": "Semiconductors & Hardware",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-18",
            "pilot_days_elapsed": 40,
            "invited_users": 50,
            "activated_users": 38,
            "weekly_active_users": 23,
            "retained_30d_users": 24,
            "workflow_time_reduction_pct": 0.15,
            "monthly_verified_outputs": 380,
            "satisfaction_score": 4.1,
            "workflow_runs_monthly": 3400,
            "weekly_wau_history": [0.56, 0.58, 0.60, 0.60, 0.61, 0.61, 0.60, 0.61],
            "stage": "Healthy but Watch",
            "champion_name": "Hana Takahashi",
            "champion_title": "Fab Cost Accounting Lead",
            "buyer_title": "VP Corporate Finance",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_nordic_paper",
            "name": "Nordic Forestry & Paper",
            "industry": "Forest Products & Packaging",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-25",
            "pilot_days_elapsed": 33,
            "invited_users": 50,
            "activated_users": 36,
            "weekly_active_users": 21,
            "retained_30d_users": 22,
            "workflow_time_reduction_pct": 0.14,
            "monthly_verified_outputs": 340,
            "satisfaction_score": 4.0,
            "workflow_runs_monthly": 3100,
            "weekly_wau_history": [0.52, 0.55, 0.57, 0.58, 0.58, 0.57, 0.58, 0.58],
            "stage": "Healthy but Watch",
            "champion_name": "Lars Lindholm",
            "champion_title": "Plant Cost Accountant",
            "buyer_title": "Finance Director",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_cascade_beverage",
            "name": "Cascade Consumer Brands",
            "industry": "Beverage & Food Processing",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-23",
            "pilot_days_elapsed": 35,
            "invited_users": 50,
            "activated_users": 37,
            "weekly_active_users": 22,
            "retained_30d_users": 23,
            "workflow_time_reduction_pct": 0.15,
            "monthly_verified_outputs": 360,
            "satisfaction_score": 4.0,
            "workflow_runs_monthly": 3250,
            "weekly_wau_history": [0.53, 0.56, 0.58, 0.59, 0.59, 0.58, 0.59, 0.59],
            "stage": "Healthy but Watch",
            "champion_name": "Jessica Bell",
            "champion_title": "Commercial FP&A Manager",
            "buyer_title": "VP Finance",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_orion_aerospace",
            "name": "Orion Aerospace Technologies",
            "industry": "Aerospace & Defense",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-19",
            "pilot_days_elapsed": 39,
            "invited_users": 50,
            "activated_users": 38,
            "weekly_active_users": 23,
            "retained_30d_users": 24,
            "workflow_time_reduction_pct": 0.16,
            "monthly_verified_outputs": 390,
            "satisfaction_score": 4.1,
            "workflow_runs_monthly": 3600,
            "weekly_wau_history": [0.55, 0.57, 0.59, 0.60, 0.60, 0.59, 0.60, 0.60],
            "stage": "Healthy but Watch",
            "champion_name": "Alan Ward",
            "champion_title": "Defense Contracts Controller",
            "buyer_title": "CFO",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_helios_power",
            "name": "Helios Utility Power",
            "industry": "Public Utilities & Generation",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-24",
            "pilot_days_elapsed": 34,
            "invited_users": 50,
            "activated_users": 35,
            "weekly_active_users": 20,
            "retained_30d_users": 21,
            "workflow_time_reduction_pct": 0.13,
            "monthly_verified_outputs": 320,
            "satisfaction_score": 3.9,
            "workflow_runs_monthly": 2900,
            "weekly_wau_history": [0.50, 0.53, 0.55, 0.56, 0.56, 0.55, 0.56, 0.56],
            "stage": "Healthy but Watch",
            "champion_name": "Rachel Adams",
            "champion_title": "Generation Finance Manager",
            "buyer_title": "VP Accounting",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_summit_materials",
            "name": "Summit Industrial Materials",
            "industry": "Specialty Chemicals",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-21",
            "pilot_days_elapsed": 37,
            "invited_users": 50,
            "activated_users": 37,
            "weekly_active_users": 22,
            "retained_30d_users": 23,
            "workflow_time_reduction_pct": 0.15,
            "monthly_verified_outputs": 370,
            "satisfaction_score": 4.0,
            "workflow_runs_monthly": 3300,
            "weekly_wau_history": [0.54, 0.56, 0.58, 0.59, 0.58, 0.59, 0.58, 0.59],
            "stage": "Healthy but Watch",
            "champion_name": "Kurt Meyer",
            "champion_title": "Polymers FP&A Lead",
            "buyer_title": "VP Financial Operations",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_trinity_insurance",
            "name": "Trinity Surety & Insurance",
            "industry": "Commercial Underwriting",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-17",
            "pilot_days_elapsed": 41,
            "invited_users": 50,
            "activated_users": 38,
            "weekly_active_users": 23,
            "retained_30d_users": 24,
            "workflow_time_reduction_pct": 0.16,
            "monthly_verified_outputs": 400,
            "satisfaction_score": 4.1,
            "workflow_runs_monthly": 3550,
            "weekly_wau_history": [0.55, 0.57, 0.59, 0.60, 0.59, 0.60, 0.59, 0.60],
            "stage": "Healthy but Watch",
            "champion_name": "Stephanie Price",
            "champion_title": "Underwriting Expense Manager",
            "buyer_title": "Chief Actuary & VP Finance",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },

        # =========================================================================
        # 6 AT RISK ACCOUNTS (Health Score < 40, Verdict: INTERVENE)
        # =========================================================================
        {
            "id": "acct_apex_global",
            "name": "Apex Global",
            "industry": "Global Logistics & Freight",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-13",
            "pilot_days_elapsed": 45,  # Exactly Day 45! Triggers mandatory SLA intervention!
            "invited_users": 50,
            "activated_users": 22,
            "weekly_active_users": 6,  # 27.3% WAU
            "retained_30d_users": 7,
            "workflow_time_reduction_pct": 0.06,  # 6% reduction
            "monthly_verified_outputs": 130,
            "satisfaction_score": 3.3,
            "workflow_runs_monthly": 1100,
            "weekly_wau_history": [0.45, 0.38, 0.32, 0.26, 0.22, 0.18, 0.15, 0.12],
            "stage": "Intervention Active",
            "champion_name": "Gregory Thorne",
            "champion_title": "Logistics Financial Controller",
            "buyer_title": "VP Supply Chain Finance",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_atlas_telecom",
            "name": "Atlas Telecom Global",
            "industry": "Telecommunications",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-14",
            "pilot_days_elapsed": 44,
            "invited_users": 50,
            "activated_users": 24,
            "weekly_active_users": 7,
            "retained_30d_users": 8,
            "workflow_time_reduction_pct": 0.07,
            "monthly_verified_outputs": 140,
            "satisfaction_score": 3.4,
            "workflow_runs_monthly": 1250,
            "weekly_wau_history": [0.45, 0.39, 0.33, 0.28, 0.24, 0.20, 0.16, 0.12],
            "stage": "At Risk",
            "champion_name": "Sonia Morales",
            "champion_title": "Infrastructure Finance Lead",
            "buyer_title": "SVP Financial Planning",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_pioneer_media",
            "name": "Pioneer Publishing & Media",
            "industry": "Publishing & Media",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-23",
            "pilot_days_elapsed": 35,
            "invited_users": 50,
            "activated_users": 25,
            "weekly_active_users": 8,
            "retained_30d_users": 9,
            "workflow_time_reduction_pct": 0.08,
            "monthly_verified_outputs": 160,
            "satisfaction_score": 3.5,
            "workflow_runs_monthly": 1400,
            "weekly_wau_history": [0.46, 0.40, 0.35, 0.30, 0.26, 0.22, 0.18, 0.14],
            "stage": "At Risk",
            "champion_name": "Arthur Pendelton",
            "champion_title": "Editorial Budget Manager",
            "buyer_title": "Chief Financial Officer",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_cobalt_mining",
            "name": "Cobalt Resources & Mining",
            "industry": "Natural Resources & Mining",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-15",
            "pilot_days_elapsed": 43,
            "invited_users": 50,
            "activated_users": 21,
            "weekly_active_users": 5,
            "retained_30d_users": 6,
            "workflow_time_reduction_pct": 0.05,
            "monthly_verified_outputs": 110,
            "satisfaction_score": 3.2,
            "workflow_runs_monthly": 950,
            "weekly_wau_history": [0.42, 0.36, 0.30, 0.24, 0.20, 0.16, 0.13, 0.10],
            "stage": "At Risk",
            "champion_name": "Simon Sterling",
            "champion_title": "Capital Projects Controller",
            "buyer_title": "VP Mineral Finance",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_harbor_shipping",
            "name": "Harbor Maritime Transit",
            "industry": "Ocean Shipping & Terminals",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-12",
            "pilot_days_elapsed": 46,
            "invited_users": 50,
            "activated_users": 23,
            "weekly_active_users": 6,
            "retained_30d_users": 7,
            "workflow_time_reduction_pct": 0.06,
            "monthly_verified_outputs": 125,
            "satisfaction_score": 3.3,
            "workflow_runs_monthly": 1050,
            "weekly_wau_history": [0.44, 0.37, 0.31, 0.25, 0.21, 0.17, 0.14, 0.11],
            "stage": "Intervention Active",
            "champion_name": "Tanya Vance",
            "champion_title": "Port Operations Controller",
            "buyer_title": "Chief Financial Officer",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
        {
            "id": "acct_horizon_retail",
            "name": "Horizon Discount Retailers",
            "industry": "Value Retail Stores",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-16",
            "pilot_days_elapsed": 42,
            "invited_users": 50,
            "activated_users": 24,
            "weekly_active_users": 7,
            "retained_30d_users": 8,
            "workflow_time_reduction_pct": 0.07,
            "monthly_verified_outputs": 135,
            "satisfaction_score": 3.4,
            "workflow_runs_monthly": 1150,
            "weekly_wau_history": [0.43, 0.38, 0.32, 0.27, 0.23, 0.19, 0.15, 0.12],
            "stage": "At Risk",
            "champion_name": "Barry Walsh",
            "champion_title": "Store Operations Financial Analyst",
            "buyer_title": "VP Store Operations Finance",
            "primary_workflow": "FP&A Variance Analysis & Management Reporting",
        },
    ]

    accounts = []
    for item in accounts_data:
        logs = generate_weekly_logs(
            account_id=item["id"],
            wau_history=item["weekly_wau_history"],
            base_users=item["activated_users"],
            base_time_saved=item["workflow_time_reduction_pct"],
        )
        acct = Account(**item, recent_logs=logs)
        accounts.append(acct)

    return accounts
