from typing import List
from app.models import Account, WeeklyLog


def generate_weekly_logs(account_id: str, wau_history: List[float], base_users: int, base_time_saved: float) -> List[WeeklyLog]:
    logs = []
    dates = [
        "2026-07-07", "2026-07-14", "2026-07-21", "2026-07-28",
        "2026-08-04", "2026-08-11", "2026-08-18", "2026-08-25"
    ]
    for i, wau_pct in enumerate(wau_history):
        active_u = int(round(wau_pct * base_users))
        tasks_started = active_u * 18 + (i * 12)
        tasks_completed = int(tasks_started * 0.94)
        active_mins = round(42.0 + (wau_pct * 30.0), 1)
        ai_calls = tasks_started * 3 + 20
        successful_outputs = int(tasks_completed * 0.96)
        time_saved = min(0.35, max(0.05, base_time_saved * (0.8 + (i * 0.05))))
        feedback = min(5.0, max(3.0, 3.8 + (wau_pct * 1.2)))

        logs.append(
            WeeklyLog(
                week_number=i + 1,
                date=dates[i % len(dates)],
                active_users=active_u,
                tasks_started=tasks_started,
                tasks_completed=tasks_completed,
                active_minutes_avg=active_mins,
                ai_calls=ai_calls,
                successful_outputs=successful_outputs,
                time_saved_pct=round(time_saved, 3),
                feedback_score=round(feedback, 1),
            )
        )
    return logs


def get_seed_accounts() -> List[Account]:
    accounts_data = [
        # --- EXPANSION READY (Score >= 70, Green) ---
        {
            "id": "acct_acme_corp",
            "name": "Acme Corp",
            "industry": "Enterprise Manufacturing & Tech",
            "tier": "Enterprise (Global 500)",
            "pilot_start_date": "2026-07-01",
            "pilot_days_elapsed": 56,
            "invited_users": 50,
            "activated_users": 48,
            "weekly_active_users": 41,  # 85.4% WAU
            "retained_30d_users": 42,   # 87.5% 30d retention
            "workflow_time_reduction_pct": 0.28,  # 28% reduction
            "monthly_verified_outputs": 740,
            "satisfaction_score": 4.7,
            "workflow_runs_monthly": 6800,
            "weekly_wau_history": [0.65, 0.70, 0.74, 0.77, 0.79, 0.82, 0.84, 0.85],
            "stage": "Expansion Ready",
            "champion_name": "Sarah Lin",
            "champion_title": "Director of FP&A Operations",
            "buyer_title": "VP Global Finance",
        },
        {
            "id": "acct_meridian_health",
            "name": "Meridian Health Systems",
            "industry": "Healthcare & Life Sciences",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-05",
            "pilot_days_elapsed": 52,
            "invited_users": 50,
            "activated_users": 46,
            "weekly_active_users": 38,
            "retained_30d_users": 39,
            "workflow_time_reduction_pct": 0.26,
            "monthly_verified_outputs": 680,
            "satisfaction_score": 4.6,
            "workflow_runs_monthly": 5900,
            "weekly_wau_history": [0.60, 0.65, 0.70, 0.74, 0.76, 0.79, 0.81, 0.83],
            "stage": "Expansion Ready",
            "champion_name": "Marcus Vance",
            "champion_title": "Head of Strategic Planning",
            "buyer_title": "Chief Financial Officer",
        },
        {
            "id": "acct_apex_logistics",
            "name": "Apex Global Logistics",
            "industry": "Transportation & Supply Chain",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-10",
            "pilot_days_elapsed": 48,
            "invited_users": 50,
            "activated_users": 45,
            "weekly_active_users": 36,
            "retained_30d_users": 37,
            "workflow_time_reduction_pct": 0.24,
            "monthly_verified_outputs": 610,
            "satisfaction_score": 4.5,
            "workflow_runs_monthly": 5400,
            "weekly_wau_history": [0.58, 0.62, 0.68, 0.71, 0.73, 0.76, 0.78, 0.80],
            "stage": "Expansion Ready",
            "champion_name": "Elena Rostova",
            "champion_title": "VP Financial Controller",
            "buyer_title": "SVP Finance",
        },
        {
            "id": "acct_crestview_fin",
            "name": "Crestview Financial Group",
            "industry": "Asset Management & Banking",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-02",
            "pilot_days_elapsed": 55,
            "invited_users": 50,
            "activated_users": 49,
            "weekly_active_users": 42,
            "retained_30d_users": 44,
            "workflow_time_reduction_pct": 0.29,
            "monthly_verified_outputs": 810,
            "satisfaction_score": 4.8,
            "workflow_runs_monthly": 7200,
            "weekly_wau_history": [0.68, 0.72, 0.76, 0.80, 0.82, 0.84, 0.85, 0.86],
            "stage": "Expansion Ready",
            "champion_name": "David Sterling",
            "champion_title": "FP&A Lead, Portfolio Strategy",
            "buyer_title": "EVP Financial Governance",
        },
        {
            "id": "acct_horizon_robotics",
            "name": "Horizon Automation Systems",
            "industry": "Industrial Hardware & AI",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-12",
            "pilot_days_elapsed": 46,
            "invited_users": 50,
            "activated_users": 47,
            "weekly_active_users": 38,
            "retained_30d_users": 39,
            "workflow_time_reduction_pct": 0.27,
            "monthly_verified_outputs": 690,
            "satisfaction_score": 4.6,
            "workflow_runs_monthly": 6100,
            "weekly_wau_history": [0.62, 0.66, 0.71, 0.75, 0.77, 0.79, 0.80, 0.81],
            "stage": "Expansion Ready",
            "champion_name": "Claire Dupont",
            "champion_title": "Senior Finance Architect",
            "buyer_title": "VP Corporate Finance",
        },
        {
            "id": "acct_vantage_media",
            "name": "Vantage Media Group",
            "industry": "Digital Media & Streaming",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-08",
            "pilot_days_elapsed": 50,
            "invited_users": 50,
            "activated_users": 44,
            "weekly_active_users": 34,
            "retained_30d_users": 35,
            "workflow_time_reduction_pct": 0.22,
            "monthly_verified_outputs": 570,
            "satisfaction_score": 4.4,
            "workflow_runs_monthly": 5100,
            "weekly_wau_history": [0.55, 0.60, 0.66, 0.70, 0.72, 0.74, 0.76, 0.77],
            "stage": "Expansion Ready",
            "champion_name": "Jordan Hayes",
            "champion_title": "Director FP&A, Content",
            "buyer_title": "VP Global FP&A",
        },
        {
            "id": "acct_omniretail",
            "name": "OmniRetail Holdings",
            "industry": "Consumer Goods & Retail",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-15",
            "pilot_days_elapsed": 44,
            "invited_users": 50,
            "activated_users": 43,
            "weekly_active_users": 33,
            "retained_30d_users": 33,
            "workflow_time_reduction_pct": 0.21,
            "monthly_verified_outputs": 540,
            "satisfaction_score": 4.3,
            "workflow_runs_monthly": 4900,
            "weekly_wau_history": [0.54, 0.58, 0.64, 0.68, 0.71, 0.73, 0.75, 0.77],
            "stage": "Expansion Ready",
            "champion_name": "Kavita Rao",
            "champion_title": "Retail Variance Manager",
            "buyer_title": "Head of Commercial Finance",
        },

        # --- HEALTHY BUT WATCH (40 <= Score < 70, Yellow) ---
        {
            "id": "acct_global_retail",
            "name": "Global Retail Partners",
            "industry": "Omnichannel Retail",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-18",
            "pilot_days_elapsed": 41,
            "invited_users": 50,
            "activated_users": 38,
            "weekly_active_users": 26,  # 68% WAU
            "retained_30d_users": 28,
            "workflow_time_reduction_pct": 0.18,  # Close to 20%
            "monthly_verified_outputs": 460,
            "satisfaction_score": 4.1,
            "workflow_runs_monthly": 3900,
            "weekly_wau_history": [0.60, 0.62, 0.65, 0.67, 0.67, 0.68, 0.68, 0.68],
            "stage": "Healthy but Watch",
            "champion_name": "Liam Gallagher",
            "champion_title": "FP&A Lead",
            "buyer_title": "VP Finance",
        },
        {
            "id": "acct_fintech_one",
            "name": "FinTech One Payment Solutions",
            "industry": "Financial Technology",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-20",
            "pilot_days_elapsed": 39,
            "invited_users": 50,
            "activated_users": 40,
            "weekly_active_users": 27,
            "retained_30d_users": 29,
            "workflow_time_reduction_pct": 0.19,
            "monthly_verified_outputs": 490,
            "satisfaction_score": 4.2,
            "workflow_runs_monthly": 4200,
            "weekly_wau_history": [0.62, 0.64, 0.66, 0.67, 0.66, 0.67, 0.67, 0.68],
            "stage": "Healthy but Watch",
            "champion_name": "Rachel Zane",
            "champion_title": "Financial Systems Lead",
            "buyer_title": "VP Finance & Operations",
        },
        {
            "id": "acct_bluesky_aviation",
            "name": "BlueSky Aviation Systems",
            "industry": "Aerospace & Defense",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-22",
            "pilot_days_elapsed": 37,
            "invited_users": 50,
            "activated_users": 36,
            "weekly_active_users": 22,
            "retained_30d_users": 24,
            "workflow_time_reduction_pct": 0.16,
            "monthly_verified_outputs": 410,
            "satisfaction_score": 4.0,
            "workflow_runs_monthly": 3400,
            "weekly_wau_history": [0.55, 0.57, 0.59, 0.61, 0.60, 0.60, 0.61, 0.61],
            "stage": "Healthy but Watch",
            "champion_name": "Frank Becker",
            "champion_title": "Operations Finance Specialist",
            "buyer_title": "VP Procurement & Finance",
        },
        {
            "id": "acct_sterling_cap",
            "name": "Sterling Capital Partners",
            "industry": "Private Equity",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-16",
            "pilot_days_elapsed": 43,
            "invited_users": 50,
            "activated_users": 42,
            "weekly_active_users": 28,
            "retained_30d_users": 30,
            "workflow_time_reduction_pct": 0.18,
            "monthly_verified_outputs": 470,
            "satisfaction_score": 4.3,
            "workflow_runs_monthly": 4100,
            "weekly_wau_history": [0.62, 0.64, 0.66, 0.67, 0.67, 0.66, 0.67, 0.67],
            "stage": "Healthy but Watch",
            "champion_name": "Tariq Mansoor",
            "champion_title": "Portfolio Reporting Manager",
            "buyer_title": "Chief Financial Officer",
        },
        {
            "id": "acct_cobalt_energy",
            "name": "Cobalt Clean Energy",
            "industry": "Renewable Energy & Utilities",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-25",
            "pilot_days_elapsed": 34,
            "invited_users": 50,
            "activated_users": 41,
            "weekly_active_users": 29,
            "retained_30d_users": 30,
            "workflow_time_reduction_pct": 0.19,
            "monthly_verified_outputs": 480,
            "satisfaction_score": 4.2,
            "workflow_runs_monthly": 4300,
            "weekly_wau_history": [0.61, 0.63, 0.66, 0.68, 0.69, 0.70, 0.70, 0.71],
            "stage": "Healthy but Watch",
            "champion_name": "Siddharth Patel",
            "champion_title": "FP&A Project Lead",
            "buyer_title": "VP Corporate Strategy",
        },
        {
            "id": "acct_nexus_dyn",
            "name": "Nexus Dynamics Software",
            "industry": "Enterprise B2B Software",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-28",
            "pilot_days_elapsed": 31,
            "invited_users": 50,
            "activated_users": 34,
            "weekly_active_users": 20,
            "retained_30d_users": 21,
            "workflow_time_reduction_pct": 0.15,
            "monthly_verified_outputs": 360,
            "satisfaction_score": 3.9,
            "workflow_runs_monthly": 3100,
            "weekly_wau_history": [0.50, 0.52, 0.54, 0.56, 0.57, 0.58, 0.58, 0.59],
            "stage": "Healthy but Watch",
            "champion_name": "Audrey Chen",
            "champion_title": "Senior Financial Analyst",
            "buyer_title": "Head of FP&A",
        },
        {
            "id": "acct_beacon_hosp",
            "name": "Beacon Hospitality International",
            "industry": "Hospitality & Leisure",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-30",
            "pilot_days_elapsed": 29,
            "invited_users": 50,
            "activated_users": 33,
            "weekly_active_users": 19,
            "retained_30d_users": 20,
            "workflow_time_reduction_pct": 0.14,
            "monthly_verified_outputs": 330,
            "satisfaction_score": 3.9,
            "workflow_runs_monthly": 2900,
            "weekly_wau_history": [0.48, 0.50, 0.52, 0.54, 0.55, 0.56, 0.57, 0.58],
            "stage": "Healthy but Watch",
            "champion_name": "Mateo Morales",
            "champion_title": "Regional Finance Controller",
            "buyer_title": "VP Corporate Finance",
        },

        # --- AT RISK / DAY 45 INTERVENTION (Red, Score < 40 or Score < 45 by Day 45) ---
        {
            "id": "acct_nova_pharma",
            "name": "Nova Pharmaceuticals",
            "industry": "Pharmaceuticals & Biotech",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-09",
            "pilot_days_elapsed": 49,  # PAST DAY 45!
            "invited_users": 50,
            "activated_users": 20,
            "weekly_active_users": 6,  # 30% WAU
            "retained_30d_users": 7,
            "workflow_time_reduction_pct": 0.05,  # 5% reduction
            "monthly_verified_outputs": 110,
            "satisfaction_score": 3.1,
            "workflow_runs_monthly": 950,
            "weekly_wau_history": [0.42, 0.36, 0.30, 0.25, 0.22, 0.18, 0.15, 0.12],
            "stage": "Intervention Active",
            "champion_name": "Dr. Aris Thorne",
            "champion_title": "R&D Finance Liaison",
            "buyer_title": "VP Global Finance",
        },
        {
            "id": "acct_vertex_capital",
            "name": "Vertex Capital Trust",
            "industry": "Commercial Banking",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-11",
            "pilot_days_elapsed": 47,  # PAST DAY 45!
            "invited_users": 50,
            "activated_users": 22,
            "weekly_active_users": 7,
            "retained_30d_users": 8,
            "workflow_time_reduction_pct": 0.06,
            "monthly_verified_outputs": 130,
            "satisfaction_score": 3.3,
            "workflow_runs_monthly": 1100,
            "weekly_wau_history": [0.44, 0.38, 0.32, 0.28, 0.25, 0.22, 0.18, 0.14],
            "stage": "Intervention Active",
            "champion_name": "Simon Lee",
            "champion_title": "Compliance Finance Director",
            "buyer_title": "Head of Regulatory Finance",
        },
        {
            "id": "acct_strata_mfg",
            "name": "Strata Heavy Manufacturing",
            "industry": "Heavy Industry & Auto",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-04",
            "pilot_days_elapsed": 54,
            "invited_users": 50,
            "activated_users": 18,
            "weekly_active_users": 5,
            "retained_30d_users": 6,
            "workflow_time_reduction_pct": 0.04,
            "monthly_verified_outputs": 90,
            "satisfaction_score": 2.9,
            "workflow_runs_monthly": 800,
            "weekly_wau_history": [0.40, 0.35, 0.30, 0.25, 0.22, 0.18, 0.15, 0.10],
            "stage": "At Risk",
            "champion_name": "Kurt Hanssen",
            "champion_title": "Plant Controller",
            "buyer_title": "VP Operations Finance",
        },
        {
            "id": "acct_atlas_telecom",
            "name": "Atlas Telecom Global",
            "industry": "Telecommunications",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-13",
            "pilot_days_elapsed": 45,  # Exactly Day 45!
            "invited_users": 50,
            "activated_users": 24,
            "weekly_active_users": 7,
            "retained_30d_users": 8,
            "workflow_time_reduction_pct": 0.07,
            "monthly_verified_outputs": 140,
            "satisfaction_score": 3.4,
            "workflow_runs_monthly": 1250,
            "weekly_wau_history": [0.45, 0.39, 0.33, 0.28, 0.24, 0.20, 0.16, 0.12],
            "stage": "Intervention Active",
            "champion_name": "Sonia Morales",
            "champion_title": "Infrastructure Finance Lead",
            "buyer_title": "SVP Financial Planning",
        },
        {
            "id": "acct_pioneer_media",
            "name": "Pioneer Publishing & Media",
            "industry": "Publishing",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-07-24",
            "pilot_days_elapsed": 35,
            "invited_users": 50,
            "activated_users": 25,
            "weekly_active_users": 8,
            "retained_30d_users": 9,
            "workflow_time_reduction_pct": 0.08,
            "monthly_verified_outputs": 160,
            "satisfaction_score": 3.5,
            "workflow_runs_monthly": 1400,
            "weekly_wau_history": [0.46, 0.40, 0.35, 0.30, 0.26, 0.22, 0.18, 0.14],
            "stage": "At Risk",
            "champion_name": "Arthur Pendelton",
            "champion_title": "Editorial Budget Manager",
            "buyer_title": "Chief Financial Officer",
        },
        {
            "id": "acct_solaris_semi",
            "name": "Solaris Semiconductor",
            "industry": "Semiconductors & Hardware",
            "tier": "Enterprise",
            "pilot_start_date": "2026-07-19",
            "pilot_days_elapsed": 40,
            "invited_users": 50,
            "activated_users": 39,
            "weekly_active_users": 27,
            "retained_30d_users": 28,
            "workflow_time_reduction_pct": 0.19,
            "monthly_verified_outputs": 470,
            "satisfaction_score": 4.2,
            "workflow_runs_monthly": 4100,
            "weekly_wau_history": [0.60, 0.63, 0.65, 0.67, 0.68, 0.69, 0.69, 0.69],
            "stage": "Healthy but Watch",
            "champion_name": "Hana Takahashi",
            "champion_title": "Fab Cost Accounting Lead",
            "buyer_title": "VP Corporate Finance",
        },
        {
            "id": "acct_zenith_logistics",
            "name": "Zenith Freight Solutions",
            "industry": "Logistics & Fleet",
            "tier": "Mid-Market",
            "pilot_start_date": "2026-08-01",
            "pilot_days_elapsed": 27,
            "invited_users": 50,
            "activated_users": 42,
            "weekly_active_users": 31,
            "retained_30d_users": 32,
            "workflow_time_reduction_pct": 0.22,
            "monthly_verified_outputs": 520,
            "satisfaction_score": 4.4,
            "workflow_runs_monthly": 4500,
            "weekly_wau_history": [0.58, 0.62, 0.66, 0.70, 0.72, 0.73, 0.74, 0.75],
            "stage": "Expansion Ready",
            "champion_name": "Dmitri Volkov",
            "champion_title": "Fleet Cost Analytics Lead",
            "buyer_title": "VP Finance",
        },
    ]

    accounts = []
    for item in accounts_data:
        logs = generate_weekly_logs(
            account_id=item["id"],
            wau_history=item["weekly_wau_history"],
            base_users=item["activated_users"],
            base_time_saved=item["workflow_time_reduction_pct"],
        )
        acct = Account(**item, recent_logs=logs)
        accounts.append(acct)

    return accounts
